import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Fingerprint, LockKeyhole, ShieldCheck } from "lucide-react";

export const metadata: Metadata = { title: "Security & privacy", description: "How GhostKey protects your secrets, what we store, and the limits of temporary secret sharing." };

export default function SecurityPage() {
  return (
    <main className="security-main">
      <Link href="/" className="subtle-link back-link"><ArrowLeft size={14} />Back to GhostKey</Link>
      <span className="status-pill"><ShieldCheck size={12} />THE SECURITY MODEL</span>
      <h1>Private by design.<br /><span>Transparent by choice.</span></h1>
      <p className="security-lead">Your secret should only be read by the person you share it with. Here’s how GhostKey makes that happen—and where its protection ends.</p>
      <div className="security-diagram" aria-label="Your browser encrypts the secret, the server stores ciphertext, and the recipient decrypts it"><div><LockKeyhole size={21} /><strong>YOUR BROWSER</strong><span>Encrypts locally</span></div><ArrowRight size={17} /><div><Fingerprint size={21} /><strong>OUR SERVER</strong><span>Ciphertext only</span></div><ArrowRight size={17} /><div><LockKeyhole size={21} /><strong>THEIR BROWSER</strong><span>Decrypts locally</span></div></div>
      <div className="security-sections">
        <section><span className="eyebrow">01 / ENCRYPTION</span><h2>The key stays in your hands.</h2><p>Your browser generates a random 256-bit key and encrypts your secret using AES-256-GCM through the Web Crypto API. Each secret gets a fresh key and a random initialization vector. GhostKey sends only the encrypted payload, its initialization vector, and your access settings to the server.</p><p>The key is placed after the <code>#</code> in the link. Browsers don’t include this URL fragment in HTTP requests. Decryption happens on the recipient’s device. Share the complete link only with someone you trust: anyone who has it has the key.</p></section>
        <section><span className="eyebrow">02 / ACCESS & EXPIRATION</span><h2>Temporary means temporary.</h2><p>A secret expires after your chosen duration, from 1 minute to 30 days. Choose one view, multiple views, or unlimited views until expiration. The server enforces these rules atomically, so simultaneous requests cannot both take the final view.</p><p>Opening a link checks its availability without consuming it. Only confirming “Reveal secret” requests the encrypted payload and spends a view. The final retrieval deletes it from the active database. Expired secrets are inaccessible immediately and are removed by scheduled cleanup within five minutes.</p><p>A view is counted when the server releases the encrypted payload. A lost connection or an incorrect key can still spend that view. The server cannot verify local decryption without receiving information it intentionally doesn’t have.</p></section>
        <section><span className="eyebrow">03 / WHAT WE STORE</span><h2>Less to keep. Less to expose.</h2><p>The active database stores ciphertext, an initialization vector, hashed link and deletion tokens, expiration, view counts, and creation time. It never stores your plaintext or encryption key. Short-lived hash-only records retain “expired” or “consumed” status for up to 24 hours after deletion.</p><p>No account, analytics, third-party scripts, or browser storage is used. Abuse protection uses short-lived, one-way identifiers derived from trusted network information; raw IP addresses are not stored by this application. Hosting providers can process standard connection metadata under their own retention policies.</p><p>Deletion removes the active encrypted record. Infrastructure backups may retain earlier ciphertext until the provider’s backup retention period ends. The encryption key is never included in those backups by GhostKey.</p></section>
        <section><span className="eyebrow">04 / ON YOUR DEVICE</span><h2>Private isn’t copy-proof.</h2><p>Revealed text lives only in this page’s memory. It clears when you leave, when the secret expires, or after five minutes—whichever comes first. You can clear it sooner. Copying a secret puts it in your system clipboard, which GhostKey cannot automatically erase.</p><p>Recipients can save, copy, or screenshot what they see. Browser extensions, compromised devices, browser history synchronization, and software with screen access are outside GhostKey’s control. The shared link itself is sensitive, so use a trusted channel to send it.</p></section>
        <section><span className="eyebrow">05 / TRUST BOUNDARIES</span><h2>A clear promise, with clear limits.</h2><p>Client-side encryption protects stored secrets from being read by the database. You still trust the site to deliver honest JavaScript and your browser to execute it safely. A compromised application host could change that code. This is not a claim of anonymity or a substitute for a dedicated password manager.</p><p>HTTPS, a restrictive Content Security Policy, isolated server credentials, and database access controls protect the intended flow. Use GhostKey for temporary sharing, and keep long-term credentials in a system designed for it.</p></section>
      </div>
      <div className="security-cta"><span>Something to share?</span><Link href="/" className="button button-primary">Create a secret <ArrowRight size={15} /></Link></div>
    </main>
  );
}

